### ISSUE TITLE
AmEx logo doesn't load on landing page on tablets

### ISSUE THREAD

**Issue by brownac** [brownac/AmExHackathon#41]
@GonzaloZiadi , @egs104 
- Why isn't the resource loading on the page on tablets?  Is it being sourced correctly?

@Jhtrink 
- What image are we even using for this page?  Isn't there an issue with the logo that we're using right now?

**Comment by Jhtrink** [comment]
Michelle doesn't want us using the Amex logo so I used a generic photo from google images. I sourced it the same way that the previous photo was sourced by putting it in the same file location. I increased the size of the image significantly which might be why it's not showing up on the tablet
