### ISSUE TITLE
SQL DB not created unless form is used

### ISSUE THREAD

**Issue by justinpons** [brownac/AmExHackathon#9]
Grunt should create the DB at startup. Instead, the app waits until the screener form is used to create the db. This causes variables to be missing in some parts of of the app. @aabmass @francis19 @Bduong30

**Comment by justinpons** [comment]
Screener form submit button not working with safari and does not post... controller? @egs104 @GonzaloZiadi

**Comment by GonzaloZiadi** [comment]
Yea it doesn't work in Safari right now. We are using es6 features not supported by Safari. We're looking into using a transpiler like Babel to compile the code into es5 that Safari supports.

**Comment by aabmass** [comment]
@GonzaloZiadi is that the cause of this issue? I could add babel into the grunt flow but it will slow down bootup for development.

An alternative is we could do dev in ES6 supporting browsers, then transpile only for production or production testing. This would be easier to set up too.

**Comment by GonzaloZiadi** [comment]
@aabmass That sounds good to me.

**Comment by aabmass** [comment]
@justintime5046 can you test it in chrome or firefox and see if that's the cause of the issue?

**Comment by justinpons** [comment]
Works in firefox... That's where I've been working out of.

Someone else is going to have to verify chrome. I don't use chrome.
